language: python

python:
  - '2.6'
  - '2.7'

before_install: 
  - sudo apt-get install libevent-dev python-dev
  - psql -c 'create database creme_fraiche;' -U postgres
  - pip install -q -r buildreqs.txt

script: "python setup.py test"

notifications:
  email:
      - david@makewhatis.com
      - captainschreck@gmail.com
